import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Lang = 'en' | 'bg';

const translations = {
  en: {
    nav: {
      dashboard: 'Dashboard',
      reservations: 'Reservations',
      rooms: 'Rooms',
      guests: 'Guests',
      billing: 'Billing',
      housekeeping: 'Housekeeping',
      reports: 'Reports',
      settings: 'Settings',
      property: 'Property',
      signOut: 'Sign out',
    },
    login: {
      tagline: 'Modern hotel management, simplified.',
      description: 'Manage reservations, rooms, guests, and operations all in one powerful platform designed for hospitality professionals.',
      welcomeBack: 'Welcome back',
      createAccount: 'Create your account',
      signInSubtitle: 'Sign in to your StayWise account',
      signUpSubtitle: 'Get started with StayWise Software',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email address',
      password: 'Password',
      enterPassword: 'Enter your password',
      signIn: 'Sign in',
      createAccountBtn: 'Create account',
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: 'Already have an account?',
      createOne: 'Create one',
      demoCredentials: 'Demo Credentials:',
      nameRequired: 'Please enter your name',
    },
    dashboard: {
      quickCheckIn: 'Quick Check-in',
      newBooking: 'New Booking',
      tryAgain: 'Try Again',
      errorLoading: 'Error loading dashboard',
      noHotel: 'No hotel selected',
      noHotelSub: 'Go to Settings to configure your property',
      roomStatus: 'Room Status',
      departures: 'Departures',
      inHouse: 'In House (Occupied)',
      arrivals: 'Arrivals',
      occupied: 'Occupied',
      available: 'Available',
      needsClean: 'Needs Clean',
      clean: 'Clean',
      maintenance: 'Maintenance',
      outOfSvc: 'Out of Svc',
      occupancy: 'Occupancy',
      expected: 'Expected',
      checkedOut: 'Checked Out',
      checkedIn: 'Checked In',
      scheduled: 'Scheduled',
      totalToday: 'Total Today',
      roomsOccupied: 'Rooms Occupied',
      adults: 'Adults',
      children: 'Children',
      today: 'Today',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      yearToDate: 'Year to Date',
      revenueLast7: 'Revenue — Last 7 Days',
      forecast14: '14-Day Forecast',
      recentActivity: 'Recent Activity',
      viewAll: 'View all',
      quickActions: 'Quick Actions',
      newReservation: 'New Reservation',
      viewRooms: 'View Rooms',
      low: 'Low',
      med: 'Med',
      high: 'High',
      full: 'Full',
      viewDetails: 'View details',
      guestsExpected: 'guests expected',
      currentOccupancy: 'Current Occupancy',
      revenue: 'Revenue',
      av: 'av.',
    },
    activity: {
      checkin: 'Checked in',
      checkout: 'Checked out',
      booking: 'New booking',
      cancelled: 'Cancelled',
      noActivity: 'No recent activity',
      room: 'Room',
    },
    reservations: {
      title: 'Reservations',
      newReservation: 'New Reservation',
      search: 'Search guests, rooms...',
      allStatuses: 'All Statuses',
      pending: 'Pending',
      confirmed: 'Confirmed',
      checkedIn: 'Checked In',
      checkedOut: 'Checked Out',
      cancelled: 'Cancelled',
      guest: 'Guest',
      room: 'Room',
      checkIn: 'Check-in',
      checkOut: 'Check-out',
      status: 'Status',
      amount: 'Amount',
      source: 'Source',
      actions: 'Actions',
      noReservations: 'No reservations found',
      noReservationsSub: 'Create a new reservation to get started',
      editReservation: 'Edit Reservation',
      viewReservation: 'View Reservation',
      cancelReservation: 'Cancel Reservation',
      checkInGuest: 'Check In',
      checkOutGuest: 'Check Out',
      nights: 'nights',
      night: 'night',
      confirmCancel: 'Are you sure you want to cancel this reservation?',
      guestName: 'Guest Name',
      roomType: 'Room Type',
      selectRoom: 'Select a room',
      adults: 'Adults',
      children: 'Children',
      baseRate: 'Base Rate',
      totalAmount: 'Total Amount',
      taxAmount: 'Tax Amount',
      discount: 'Discount',
      paymentMethod: 'Payment Method',
      paymentStatus: 'Payment Status',
      amountPaid: 'Amount Paid',
      bookingSource: 'Booking Source',
      specialRequests: 'Special Requests',
      confirmationCode: 'Confirmation Code',
      save: 'Save',
      cancel: 'Cancel',
      newGuest: 'New Guest',
      existingGuest: 'Existing Guest',
    },
    rooms: {
      title: 'Rooms',
      addRoom: 'Add Room',
      search: 'Search rooms...',
      allStatuses: 'All Statuses',
      available: 'Available',
      occupied: 'Occupied',
      dirty: 'Dirty',
      cleaning: 'Cleaning',
      maintenance: 'Maintenance',
      outOfService: 'Out of Service',
      roomNumber: 'Room Number',
      type: 'Type',
      floor: 'Floor',
      capacity: 'Capacity',
      rate: 'Rate',
      status: 'Status',
      amenities: 'Amenities',
      actions: 'Actions',
      noRooms: 'No rooms found',
      noRoomsSub: 'Add rooms to get started',
      editRoom: 'Edit Room',
      deleteRoom: 'Delete Room',
      confirmDelete: 'Are you sure you want to delete this room?',
      save: 'Save',
      cancel: 'Cancel',
      perNight: 'per night',
    },
    guests: {
      title: 'Guests',
      addGuest: 'Add Guest',
      search: 'Search guests...',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      nationality: 'Nationality',
      totalStays: 'Total Stays',
      totalSpent: 'Total Spent',
      lastStay: 'Last Stay',
      vip: 'VIP',
      actions: 'Actions',
      noGuests: 'No guests found',
      noGuestsSub: 'Add guests to get started',
      editGuest: 'Edit Guest',
      deleteGuest: 'Delete Guest',
      viewHistory: 'View History',
      confirmDelete: 'Are you sure you want to delete this guest?',
      firstName: 'First Name',
      lastName: 'Last Name',
      dateOfBirth: 'Date of Birth',
      address: 'Address',
      city: 'City',
      country: 'Country',
      idNumber: 'ID Number',
      notes: 'Notes',
      save: 'Save',
      cancel: 'Cancel',
      stayHistory: 'Stay History',
    },
    billing: {
      title: 'Billing',
      newInvoice: 'New Invoice',
      search: 'Search invoices...',
      allStatuses: 'All Statuses',
      pending: 'Pending',
      paid: 'Paid',
      overdue: 'Overdue',
      partial: 'Partial',
      invoiceNumber: 'Invoice #',
      guest: 'Guest',
      room: 'Room',
      checkIn: 'Check-in',
      checkOut: 'Check-out',
      amount: 'Amount',
      status: 'Status',
      actions: 'Actions',
      noInvoices: 'No invoices found',
      noInvoicesSub: 'Invoices will appear here',
      viewInvoice: 'View Invoice',
      markPaid: 'Mark as Paid',
      download: 'Download',
      roomCharges: 'Room Charges',
      taxes: 'Taxes',
      discount: 'Discount',
      total: 'Total',
      amountPaid: 'Amount Paid',
      balance: 'Balance Due',
      paymentMethod: 'Payment Method',
      notes: 'Notes',
      save: 'Save',
      cancel: 'Cancel',
    },
    housekeeping: {
      title: 'Housekeeping',
      addTask: 'Add Task',
      search: 'Search tasks...',
      allStatuses: 'All Statuses',
      pending: 'Pending',
      inProgress: 'In Progress',
      completed: 'Completed',
      room: 'Room',
      type: 'Type',
      priority: 'Priority',
      assignedTo: 'Assigned To',
      status: 'Status',
      notes: 'Notes',
      actions: 'Actions',
      noTasks: 'No tasks found',
      noTasksSub: 'All rooms are clean',
      editTask: 'Edit Task',
      deleteTask: 'Delete Task',
      startTask: 'Start Task',
      completeTask: 'Complete Task',
      confirmDelete: 'Are you sure you want to delete this task?',
      cleaning: 'Cleaning',
      inspection: 'Inspection',
      maintenance: 'Maintenance',
      turndown: 'Turndown',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      urgent: 'Urgent',
      save: 'Save',
      cancel: 'Cancel',
      unassigned: 'Unassigned',
      checklist: 'Checklist',
    },
    reports: {
      title: 'Reports',
      occupancy: 'Occupancy',
      revenue: 'Revenue',
      guests: 'Guests',
      bookingSources: 'Booking Sources',
      housekeeping: 'Housekeeping',
      financial: 'Financial',
      cancellations: 'Cancellations',
      dateRange: 'Date Range',
      export: 'Export',
      today: 'Today',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      lastMonth: 'Last Month',
      custom: 'Custom',
      totalRevenue: 'Total Revenue',
      avgDailyRate: 'Avg Daily Rate',
      revPAR: 'RevPAR',
      occupancyRate: 'Occupancy Rate',
      totalReservations: 'Total Reservations',
      newGuests: 'New Guests',
      repeatGuests: 'Repeat Guests',
      avgLOS: 'Avg Length of Stay',
      noData: 'No data available for this period',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Manage your hotel configuration and preferences',
      hotelSettings: 'Hotel Settings',
      roomTypes: 'Room Types & Rates',
      taxConfig: 'Tax Configuration',
      users: 'Users & Permissions',
      emails: 'Email Templates',
      payment: 'Payment Settings',
      notifications: 'Notifications',
      preferences: 'System Preferences',
      hotelName: 'Hotel Name',
      starRating: 'Star Rating',
      address: 'Address',
      city: 'City',
      country: 'Country',
      phone: 'Phone',
      email: 'Email',
      website: 'Website',
      checkInTime: 'Check-in Time',
      checkOutTime: 'Check-out Time',
      currency: 'Currency',
      timezone: 'Timezone',
      cancellationPolicy: 'Cancellation Policy',
      paymentPolicy: 'Payment Policy',
      createHotel: 'Create Hotel',
      saveChanges: 'Save Changes',
      noHotelYet: 'No hotel configured yet. Fill in your hotel details and click "Create Hotel" to get started.',
      stars: 'Stars',
      star: 'Star',
      addRoomType: 'Add Room Type',
      roomTypeName: 'Room Type Name',
      baseRate: 'Base Rate',
      maxOccupancy: 'Max Occupancy',
      description: 'Description',
      taxRate: 'Tax Rate (%)',
      taxName: 'Tax Name',
      addTax: 'Add Tax',
      inviteUser: 'Invite User',
      role: 'Role',
      active: 'Active',
      inactive: 'Inactive',
      admin: 'Admin',
      manager: 'Manager',
      receptionist: 'Receptionist',
      housekeeping: 'Housekeeping',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
    },
    common: {
      loading: 'Loading...',
      error: 'An error occurred',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      filter: 'Filter',
      export: 'Export',
      close: 'Close',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
      noData: 'No data found',
      perPage: 'per page',
      page: 'Page',
      of: 'of',
      previous: 'Previous',
      next: 'Next',
      actions: 'Actions',
    },
  },
  bg: {
    nav: {
      dashboard: 'Табло',
      reservations: 'Резервации',
      rooms: 'Стаи',
      guests: 'Гости',
      billing: 'Фактуриране',
      housekeeping: 'Почистване',
      reports: 'Отчети',
      settings: 'Настройки',
      property: 'Обект',
      signOut: 'Изход',
    },
    login: {
      tagline: 'Модерно управление на хотел, опростено.',
      description: 'Управлявайте резервации, стаи, гости и операции в една мощна платформа, създадена за хотелиери.',
      welcomeBack: 'Добре дошли',
      createAccount: 'Създайте акаунт',
      signInSubtitle: 'Влезте в своя StayWise акаунт',
      signUpSubtitle: 'Започнете работа с StayWise',
      firstName: 'Име',
      lastName: 'Фамилия',
      email: 'Имейл адрес',
      password: 'Парола',
      enterPassword: 'Въведете вашата парола',
      signIn: 'Вход',
      createAccountBtn: 'Създай акаунт',
      dontHaveAccount: 'Нямате акаунт?',
      alreadyHaveAccount: 'Вече имате акаунт?',
      createOne: 'Създайте',
      demoCredentials: 'Демо данни:',
      nameRequired: 'Моля, въведете вашето име',
    },
    dashboard: {
      quickCheckIn: 'Бърз чекин',
      newBooking: 'Нова резервация',
      tryAgain: 'Опитайте отново',
      errorLoading: 'Грешка при зареждане',
      noHotel: 'Няма избран хотел',
      noHotelSub: 'Отидете в Настройки, за да конфигурирате обекта',
      roomStatus: 'Статус на стаите',
      departures: 'Заминавания',
      inHouse: 'Настанени (Заети)',
      arrivals: 'Пристигания',
      occupied: 'Заети',
      available: 'Свободни',
      needsClean: 'За почистване',
      clean: 'Чисти',
      maintenance: 'Поддръжка',
      outOfSvc: 'Извън употреба',
      occupancy: 'Заетост',
      expected: 'Очаквани',
      checkedOut: 'Напуснали',
      checkedIn: 'Настанени',
      scheduled: 'Планирани',
      totalToday: 'Общо днес',
      roomsOccupied: 'Заети стаи',
      adults: 'Възрастни',
      children: 'Деца',
      today: 'Днес',
      thisWeek: 'Тази седмица',
      thisMonth: 'Този месец',
      yearToDate: 'От началото на годината',
      revenueLast7: 'Приходи — Последните 7 дни',
      forecast14: 'Прогноза 14 дни',
      recentActivity: 'Последна активност',
      viewAll: 'Виж всички',
      quickActions: 'Бързи действия',
      newReservation: 'Нова резервация',
      viewRooms: 'Виж стаите',
      low: 'Ниска',
      med: 'Средна',
      high: 'Висока',
      full: 'Пълно',
      viewDetails: 'Детайли',
      guestsExpected: 'очаквани гости',
      currentOccupancy: 'Текуща заетост',
      revenue: 'Приходи',
      av: 'св.',
    },
    activity: {
      checkin: 'Настанен',
      checkout: 'Напуснал',
      booking: 'Нова резервация',
      cancelled: 'Отказана',
      noActivity: 'Няма последна активност',
      room: 'Стая',
    },
    reservations: {
      title: 'Резервации',
      newReservation: 'Нова резервация',
      search: 'Търсене по гост, стая...',
      allStatuses: 'Всички статуси',
      pending: 'Изчакващи',
      confirmed: 'Потвърдени',
      checkedIn: 'Настанени',
      checkedOut: 'Напуснали',
      cancelled: 'Отказани',
      guest: 'Гост',
      room: 'Стая',
      checkIn: 'Пристигане',
      checkOut: 'Заминаване',
      status: 'Статус',
      amount: 'Сума',
      source: 'Източник',
      actions: 'Действия',
      noReservations: 'Няма намерени резервации',
      noReservationsSub: 'Създайте нова резервация, за да започнете',
      editReservation: 'Редактиране',
      viewReservation: 'Преглед',
      cancelReservation: 'Отказване',
      checkInGuest: 'Настаняване',
      checkOutGuest: 'Напускане',
      nights: 'нощувки',
      night: 'нощувка',
      confirmCancel: 'Сигурни ли сте, че искате да откажете тази резервация?',
      guestName: 'Име на госта',
      roomType: 'Тип стая',
      selectRoom: 'Изберете стая',
      adults: 'Възрастни',
      children: 'Деца',
      baseRate: 'Базова цена',
      totalAmount: 'Обща сума',
      taxAmount: 'Данък',
      discount: 'Отстъпка',
      paymentMethod: 'Начин на плащане',
      paymentStatus: 'Статус на плащане',
      amountPaid: 'Платена сума',
      bookingSource: 'Източник',
      specialRequests: 'Специални изисквания',
      confirmationCode: 'Код за потвърждение',
      save: 'Запазване',
      cancel: 'Отказ',
      newGuest: 'Нов гост',
      existingGuest: 'Съществуващ гост',
    },
    rooms: {
      title: 'Стаи',
      addRoom: 'Добавяне на стая',
      search: 'Търсене на стаи...',
      allStatuses: 'Всички статуси',
      available: 'Свободна',
      occupied: 'Заета',
      dirty: 'Мръсна',
      cleaning: 'Почиства се',
      maintenance: 'Поддръжка',
      outOfService: 'Извън употреба',
      roomNumber: 'Номер на стая',
      type: 'Тип',
      floor: 'Етаж',
      capacity: 'Капацитет',
      rate: 'Цена',
      status: 'Статус',
      amenities: 'Удобства',
      actions: 'Действия',
      noRooms: 'Няма намерени стаи',
      noRoomsSub: 'Добавете стаи, за да започнете',
      editRoom: 'Редактиране',
      deleteRoom: 'Изтриване',
      confirmDelete: 'Сигурни ли сте, че искате да изтриете тази стая?',
      save: 'Запазване',
      cancel: 'Отказ',
      perNight: 'на нощ',
    },
    guests: {
      title: 'Гости',
      addGuest: 'Добавяне на гост',
      search: 'Търсене на гости...',
      name: 'Имe',
      email: 'Имейл',
      phone: 'Телефон',
      nationality: 'Националност',
      totalStays: 'Общо нощувки',
      totalSpent: 'Общо похарчено',
      lastStay: 'Последен престой',
      vip: 'ВИП',
      actions: 'Действия',
      noGuests: 'Няма намерени гости',
      noGuestsSub: 'Добавете гости, за да започнете',
      editGuest: 'Редактиране',
      deleteGuest: 'Изтриване',
      viewHistory: 'История',
      confirmDelete: 'Сигурни ли сте, че искате да изтриете този гост?',
      firstName: 'Име',
      lastName: 'Фамилия',
      dateOfBirth: 'Дата на раждане',
      address: 'Адрес',
      city: 'Град',
      country: 'Държава',
      idNumber: 'ЕГН/ЛК',
      notes: 'Бележки',
      save: 'Запазване',
      cancel: 'Отказ',
      stayHistory: 'История на престоя',
    },
    billing: {
      title: 'Фактуриране',
      newInvoice: 'Нова фактура',
      search: 'Търсене на фактури...',
      allStatuses: 'Всички статуси',
      pending: 'Изчакваща',
      paid: 'Платена',
      overdue: 'Просрочена',
      partial: 'Частично',
      invoiceNumber: 'Фактура №',
      guest: 'Гост',
      room: 'Стая',
      checkIn: 'Пристигане',
      checkOut: 'Заминаване',
      amount: 'Сума',
      status: 'Статус',
      actions: 'Действия',
      noInvoices: 'Няма намерени фактури',
      noInvoicesSub: 'Фактурите ще се покажат тук',
      viewInvoice: 'Преглед',
      markPaid: 'Маркирай като платено',
      download: 'Изтегляне',
      roomCharges: 'Такси за стаята',
      taxes: 'Данъци',
      discount: 'Отстъпка',
      total: 'Общо',
      amountPaid: 'Платено',
      balance: 'Остатък',
      paymentMethod: 'Начин на плащане',
      notes: 'Бележки',
      save: 'Запазване',
      cancel: 'Отказ',
    },
    housekeeping: {
      title: 'Почистване',
      addTask: 'Добавяне на задача',
      search: 'Търсене на задачи...',
      allStatuses: 'Всички статуси',
      pending: 'Изчакваща',
      inProgress: 'В процес',
      completed: 'Завършена',
      room: 'Стая',
      type: 'Тип',
      priority: 'Приоритет',
      assignedTo: 'Назначена на',
      status: 'Статус',
      notes: 'Бележки',
      actions: 'Действия',
      noTasks: 'Няма намерени задачи',
      noTasksSub: 'Всички стаи са чисти',
      editTask: 'Редактиране',
      deleteTask: 'Изтриване',
      startTask: 'Започни',
      completeTask: 'Завърши',
      confirmDelete: 'Сигурни ли сте, че искате да изтриете тази задача?',
      cleaning: 'Почистване',
      inspection: 'Проверка',
      maintenance: 'Поддръжка',
      turndown: 'Вечерна подготовка',
      low: 'Нисък',
      medium: 'Среден',
      high: 'Висок',
      urgent: 'Спешен',
      save: 'Запазване',
      cancel: 'Отказ',
      unassigned: 'Неназначена',
      checklist: 'Контролен списък',
    },
    reports: {
      title: 'Отчети',
      occupancy: 'Заетост',
      revenue: 'Приходи',
      guests: 'Гости',
      bookingSources: 'Източници',
      housekeeping: 'Почистване',
      financial: 'Финансови',
      cancellations: 'Откази',
      dateRange: 'Период',
      export: 'Експорт',
      today: 'Днес',
      thisWeek: 'Тази седмица',
      thisMonth: 'Този месец',
      lastMonth: 'Миналия месец',
      custom: 'По избор',
      totalRevenue: 'Общи приходи',
      avgDailyRate: 'Средна дневна цена',
      revPAR: 'RevPAR',
      occupancyRate: 'Процент заетост',
      totalReservations: 'Общо резервации',
      newGuests: 'Нови гости',
      repeatGuests: 'Повторни гости',
      avgLOS: 'Средна продължителност',
      noData: 'Няма данни за периода',
    },
    settings: {
      title: 'Настройки',
      subtitle: 'Управление на конфигурацията и предпочитанията на хотела',
      hotelSettings: 'Настройки на хотела',
      roomTypes: 'Типове стаи и цени',
      taxConfig: 'Данъчна конфигурация',
      users: 'Потребители и права',
      emails: 'Имейл шаблони',
      payment: 'Настройки за плащане',
      notifications: 'Известия',
      preferences: 'Системни предпочитания',
      hotelName: 'Наименование на хотела',
      starRating: 'Звезди',
      address: 'Адрес',
      city: 'Град',
      country: 'Държава',
      phone: 'Телефон',
      email: 'Имейл',
      website: 'Уебсайт',
      checkInTime: 'Час на настаняване',
      checkOutTime: 'Час на напускане',
      currency: 'Валута',
      timezone: 'Часова зона',
      cancellationPolicy: 'Политика за отказване',
      paymentPolicy: 'Политика за плащане',
      createHotel: 'Създаване на хотел',
      saveChanges: 'Запазване на промените',
      noHotelYet: 'Все още няма конфигуриран хотел. Попълнете данните и натиснете "Създаване на хотел".',
      stars: 'Звезди',
      star: 'Звезда',
      addRoomType: 'Добавяне на тип стая',
      roomTypeName: 'Наименование',
      baseRate: 'Базова цена',
      maxOccupancy: 'Макс. капацитет',
      description: 'Описание',
      taxRate: 'Данъчна ставка (%)',
      taxName: 'Наименование на данък',
      addTax: 'Добавяне на данък',
      inviteUser: 'Покани потребител',
      role: 'Роля',
      active: 'Активен',
      inactive: 'Неактивен',
      admin: 'Администратор',
      manager: 'Мениджър',
      receptionist: 'Рецепционист',
      housekeeping: 'Почистване',
      save: 'Запазване',
      cancel: 'Отказ',
      delete: 'Изтриване',
      edit: 'Редактиране',
      add: 'Добавяне',
      hotelName2: 'Наименование на хотела',
    },
    common: {
      loading: 'Зареждане...',
      error: 'Възникна грешка',
      save: 'Запазване',
      cancel: 'Отказ',
      delete: 'Изтриване',
      edit: 'Редактиране',
      add: 'Добавяне',
      search: 'Търсене',
      filter: 'Филтър',
      export: 'Експорт',
      close: 'Затвори',
      confirm: 'Потвърди',
      yes: 'Да',
      no: 'Не',
      noData: 'Няма намерени данни',
      perPage: 'на страница',
      page: 'Страница',
      of: 'от',
      previous: 'Предишна',
      next: 'Следваща',
      actions: 'Действия',
    },
  },
};

export type Translations = typeof translations.en;

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem('sw_lang');
    return (stored === 'bg' || stored === 'en') ? stored : 'en';
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('sw_lang', l);
  };

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
