export const CHANNEL_ICONS: Record<string, { color: string; letter: string; name: string }> = {
  booking_com:         { color: '#003580', letter: 'B',  name: 'Booking.com' },
  expedia:             { color: '#FFC72C', letter: 'E',  name: 'Expedia' },
  hotels_com:          { color: '#D9182D', letter: 'H',  name: 'Hotels.com' },
  agoda:               { color: '#CC0000', letter: 'AG', name: 'Agoda' },
  trip_com:            { color: '#007DFF', letter: 'T',  name: 'Trip.com' },
  hrs:                 { color: '#E30613', letter: 'HR', name: 'HRS' },
  hotelbeds:           { color: '#E8452C', letter: 'HB', name: 'Hotelbeds' },
  lastminute:          { color: '#E60000', letter: 'LM', name: 'Lastminute' },
  edreams:             { color: '#FF6900', letter: 'ED', name: 'eDreams' },
  despegar:            { color: '#1A98FF', letter: 'DE', name: 'Despegar' },
  airbnb:              { color: '#FF5A5F', letter: 'AB', name: 'Airbnb' },
  vrbo:                { color: '#1B5EFF', letter: 'VR', name: 'Vrbo' },
  homeaway:            { color: '#F5A623', letter: 'HA', name: 'HomeAway' },
  tripadvisor_rentals: { color: '#34E0A1', letter: 'TA', name: 'TripAdvisor Rentals' },
  plum_guide:          { color: '#2D2D2D', letter: 'PG', name: 'Plum Guide' },
  holidu:              { color: '#FF5B24', letter: 'HO', name: 'Holidu' },
  google_hotels:       { color: '#4285F4', letter: 'G',  name: 'Google Hotels' },
  tripadvisor:         { color: '#34E0A1', letter: 'TR', name: 'TripAdvisor' },
  trivago:             { color: '#E8002B', letter: 'TV', name: 'Trivago' },
  kayak:               { color: '#FF690F', letter: 'KY', name: 'Kayak' },
  skyscanner:          { color: '#0770E3', letter: 'SK', name: 'Skyscanner' },
  hotelscombined:      { color: '#FFAA00', letter: 'HC', name: 'HotelsCombined' },
  siteminder:          { color: '#0066CC', letter: 'SM', name: 'SiteMinder' },
  cloudbeds:           { color: '#FF6B2B', letter: 'CB', name: 'Cloudbeds' },
  lodgify:             { color: '#7C3AED', letter: 'LO', name: 'Lodgify' },
  rentals_united:      { color: '#2196F3', letter: 'RU', name: 'Rentals United' },
  beds24:              { color: '#1976D2', letter: 'B2', name: 'Beds24' },
  octorate:            { color: '#FF5722', letter: 'OC', name: 'Octorate' },
  smoobu:              { color: '#00BCD4', letter: 'SB', name: 'Smoobu' },
  hostaway:            { color: '#1B3A6B', letter: 'HW', name: 'Hostaway' },
  igms:                { color: '#6C63FF', letter: 'IG', name: 'iGMS' },
  guesty:              { color: '#00B4D8', letter: 'GU', name: 'Guesty' },
  amadeus:             { color: '#005FAD', letter: 'AM', name: 'Amadeus' },
  sabre:               { color: '#003087', letter: 'SA', name: 'Sabre' },
  travelport:          { color: '#0052CC', letter: 'GP', name: 'Travelport' },
  direct_website:      { color: '#10B981', letter: 'DW', name: 'Direct (Website)' },
  walk_in:             { color: '#6366F1', letter: 'WI', name: 'Walk-in' },
  phone_email:         { color: '#8B5CF6', letter: 'PE', name: 'Phone / Email' },
  travel_agent:        { color: '#F59E0B', letter: 'TA', name: 'Travel Agent' },
  corporate_contract:  { color: '#0EA5E9', letter: 'CC', name: 'Corporate' },
};

export function getChannelIcon(type: string): { color: string; letter: string; name: string } {
  return CHANNEL_ICONS[type] ?? { color: '#6B7280', letter: '?', name: type };
}
